version: 2
updates:
  # Maintain dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
