name: Docker

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * 6' # utc for midnignt saturday
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.5.0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: base
        uses: docker/build-push-action@v4
        with:
          context: base/
          push: true
          tags: project5/base:latest
      -
        name: build
        uses: docker/build-push-action@v4
        with:
          context: build/
          push: true
          tags: project5/build:latest
      -
        name: dev
        uses: docker/build-push-action@v4
        with:
          context: dev/
          push: true
          tags: project5/dev:latest
      -
        name: dind
        uses: docker/build-push-action@v4
        with:
          context: dind/
          push: true
          tags: project5/dind:latest
      -
        name: music
        uses: docker/build-push-action@v4
        with:
          context: music/
          push: true
          tags: project5/music:latest
      -
        name: sshd
        uses: docker/build-push-action@v4
        with:
          context: sshd/
          push: true
          tags: project5/sshd:latest
      -
        name: sslh
        uses: docker/build-push-action@v4
        with:
          context: sslh/
          push: true
          tags: project5/sslh:latest
      -
        name: wine
        uses: docker/build-push-action@v4
        with:
          context: wine/
          push: true
          tags: project5/wine:latest
